imagepreviewplugin: include QWebFrame
To fix build:
src/plugins/generic/imagepreviewplugin/ScrollKeeper.cpp:48:26: error: invalid use of incomplete type 'class QWebFrame'
  scrollPos_ = mainFrame_->scrollBarValue(Qt::Vertical);
                           ^~~~~~~~~~~~~~

This was broken by 146b1a5f38ea18a12bf23d989f27c1198cc6dac8.

Signed-off-by: Jiri Slaby <jirislaby@gmail.com>